-- KS-3234. /precision не грузит пазлы с фильтром «Спасение в ничью»
-- (themes LIKE '%saveEquality%') — фронт получает таймаут.
--
-- Диагностика на проде (2026-05-22):
--   GET /puzzles/browse?themes=saveEquality                → ~40c
--   GET /puzzles/browse?themes=saveEquality&source=generated → 0.13c
--   GET /puzzles/browse?themes=convertAdvantage            → 0.14c
--   GET /puzzles/browse?themes=mateIn1                     → 0.36c
--
-- Корень: после KS-2557 на `puzzles` есть индекс `puzzles_created_at_idx`,
-- и planner для `ORDER BY p.created_at DESC LIMIT 21` берёт Backward
-- Index Scan, пробегая строки по убыванию даты и фильтруя по LIKE.
-- Для популярных тем (lichess: mateIn1; convertAdvantage у нас) — top-21
-- набирается за миллисекунды. Для редких подстрок (`saveEquality` — у
-- нас сейчас немного таких пазлов, а в индексе сверху массив свежих
-- lichess-импортов) — planner перебирает миллионы строк перед тем как
-- набрать LIMIT. Гипотеза «битый пазл валит весь list-запрос» (см.
-- описание KS-3234) не подтвердилась — HTTP 200 отдаётся, но фронт
-- считает таймаут ошибкой.
--
-- Фикс: GIN pg_trgm индекс на `puzzles.themes`. Planner для LIKE с
-- substring сможет идти через GIN — найти все строки с подстрокой за
-- миллисекунды, потом отсортировать по created_at и взять LIMIT.
--
-- Так же, как KS-2093 для `archive_games` (white_name/black_name/event)
-- — там тот же шаблон.
--
-- pg_trgm extension включаем явно: на kingside DB (отдельная от
-- archive_games) он мог быть не активен. CREATE EXTENSION IF NOT
-- EXISTS — идемпотентно, requires superuser. Если у DB-роли нет SUPERUSER
-- — devops может выполнить `CREATE EXTENSION pg_trgm;` руками один раз,
-- следующий `prisma migrate deploy` повторно безопасно перепустит.
--
-- Первый деплой этой миграции упал: Prisma migrate (kingside DB)
-- оборачивает .sql целиком в транзакцию — CREATE INDEX CONCURRENTLY
-- запрещён в транзакции (`PG: CREATE INDEX CONCURRENTLY cannot run
-- inside a transaction block`). У archive-db (KS-2093) поведение
-- другое, поэтому пример оттуда не сработал.
--
-- Делаем обычный CREATE INDEX. Он берёт SHARE lock — блокирует только
-- writes на `puzzles` (INSERT/UPDATE/DELETE), SELECT'ы идут.
-- Writes в puzzles нечастые: batch-импорт (CLI generate-puzzles-from-twic,
-- запускается оператором) и POST /puzzles/batch от клиентского
-- генератора. На время сборки индекса (минуты на 6M строк) импорты
-- встанут в очередь, юзерский read-трафик /puzzles/* не пострадает.
-- Это приемлемо разово в обмен на устранение 40-секундного слоу-запроса
-- /puzzles/browse?themes=saveEquality.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS puzzles_themes_trgm_idx
  ON puzzles USING gin (themes gin_trgm_ops);
