import type { LessonFixture } from '../../../fixture-types';

const BLOCK = 'piece-values';
const BASE = 'lessons.beginner';

export const block03PieceValues: LessonFixture[] = [
  // 3.1 Ценность фигур
  {
    slug: 'piece-values',
    order: 12,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 8,
    titleKey: `${BASE}.piece-values.title`,
    summaryKey: `${BASE}.piece-values.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Шахматные фигуры сильно отличаются по возможностям. Чтобы понимать, выгоден ли размен или жертва, игроки пользуются **условной шкалой ценности**.',
            '',
            '| Фигура | Ценность |',
            '|--------|----------|',
            '| Пешка | 1 |',
            '| Конь | 3 |',
            '| Слон | 3 |',
            '| Ладья | 5 |',
            '| Ферзь | 9 |',
            '| Король | бесценен (нельзя потерять) |',
            '',
            '**Это ориентир, а не жёсткое правило.** Ценность меняется от позиции: слон в открытой позиции может быть сильнее коня, конь — сильнее в запертой структуре, ладья — особенно сильна на открытой линии, ферзь в ограниченной позиции — обычный.',
            '',
            '**Зачем знать шкалу.** Чтобы быстро оценивать размены и жертвы:',
            '- Отдал коня (3), взял слона (3) — равный размен.',
            '- Отдал ладью (5), взял слона (3) — потеря качества (минус 2).',
            '- Отдал ферзя (9), взял ладью и слона (5+3=8) — небольшая потеря (минус 1), не всегда плохо, если получил взамен инициативу или атаку.',
            '',
            '**Пара слонов.** Два слона стоят примерно на **полпункта дороже**, чем слон и конь или два коня. В открытой позиции пара слонов особенно сильна. Если можешь разменять одного слона противника, оставив ему коня, — обычно это выгодно.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: у белых слон и конь, у чёрных два слона. Позиция открытая — у чёрных небольшой, но стабильный перевес.',
          ].join('\n'),
          diagrams: [
            { fen: '4k3/pp3ppp/2b5/8/8/2N2B2/PP3PPP/4K3 w - - 0 1', caption: 'У чёрных пара слонов в открытой позиции — небольшой, но устойчивый плюс.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.piece-values.quiz.q1.prompt`,
              options: ['a','b','c','d'].map((o) => ({ id: o, labelI18nKey: `${BASE}.piece-values.quiz.q1.opt.${o}` })),
              correctOptionIds: ['c'], explanationI18nKey: `${BASE}.piece-values.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.piece-values.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.piece-values.quiz.q2.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.piece-values.quiz.q2.explanation` },
            { id: 'q3', promptI18nKey: `${BASE}.piece-values.quiz.q3.prompt`,
              options: ['a','b','c','d'].map((o) => ({ id: o, labelI18nKey: `${BASE}.piece-values.quiz.q3.opt.${o}` })),
              correctOptionIds: ['d'], multi: true, explanationI18nKey: `${BASE}.piece-values.quiz.q3.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },

  // 3.2 Размены
  {
    slug: 'exchanges',
    order: 13,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.exchanges.title`,
    summaryKey: `${BASE}.exchanges.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Размен — ситуация, когда обе стороны берут одну или несколько фигур. Правильно оценить размен — один из главных навыков.',
            '',
            '**Счёт «атакующих и защитников».** Прежде чем брать на поле, посчитай:',
            '- Сколько фигур противника нападают на это поле?',
            '- Сколько твоих фигур защищают?',
            '- В каком порядке они будут брать?',
            '- Кто остался с большим «плюсом»?',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: на поле e5 стоит чёрная пешка. На неё нападают белый конь f3 и пешка d4 — двое. Защищают её конь c6 и пешка d6 — тоже двое. Если белые берут dxe5 dxe5 Nxe5 Nxe5 — размен пешек и коней, материал равен.',
            '',
            '**Основные ориентиры:**',
            '',
            '1. **Ты в выигрышной позиции — упрощай.** Размен уменьшает количество фигур и сокращает шансы противника на контригру. В эндшпиле с лишним материалом задача техники — довести до победы, а лишние фигуры только мешают.',
            '',
            '2. **Ты в проигрышной позиции — избегай упрощений.** Чем больше фигур на доске, тем больше шансов запутать противника и создать угрозы. Разменивая всё, ты приближаешь поражение.',
            '',
            '3. **Меняй плохую фигуру на хорошую фигуру противника.** Если у тебя плохой слон (уперся в свои пешки) и есть возможность разменять его на активного слона противника — обычно делай это.',
            '',
            '4. **Не меняй без цели.** Если ни то, ни другое не выполняется — оцени позицию внимательнее. Бесцельный размен часто ухудшает позицию.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: у белых плохой слон c1 упирается в свои пешки. Разменять его на активного чернопольного слона противника — хорошая идея.',
          ].join('\n'),
          diagrams: [
            { fen: 'r1bqkbnr/ppp2ppp/2np4/4p3/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 4', caption: 'Поле e5: двое нападают, двое защищают. Серия разменов — материал равен.', orientation: 'white' },
            { fen: 'r2qk2r/ppp1bppp/2n5/3pp3/3P4/2N1P3/PPP1BPPP/R1BQK2R w KQkq - 0 1', caption: 'Белый слон c1 плохой (пешка e3, d4 — на тёмных полях). Разменять его на чёрного слона e7 выгодно.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.exchanges.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.exchanges.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.exchanges.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.exchanges.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.exchanges.quiz.q2.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.exchanges.quiz.q2.explanation` },
            { id: 'q3', promptI18nKey: `${BASE}.exchanges.quiz.q3.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.exchanges.quiz.q3.opt.${o}` })),
              correctOptionIds: ['c'], explanationI18nKey: `${BASE}.exchanges.quiz.q3.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },

  // 3.3 Висячие фигуры
  {
    slug: 'hanging-pieces',
    order: 14,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.hanging-pieces.title`,
    summaryKey: `${BASE}.hanging-pieces.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Висячая фигура** — это незащищённая фигура, которую противник может забрать бесплатно или с выгодой для себя.',
            '',
            'Самая частая ошибка новичков — оставить фигуру под боем и не заметить этого. Простая привычка **«сканировать доску»** перед каждым ходом избавит тебя от большинства таких потерь.',
            '',
            '**Правило «проверки перед ходом»:**',
            '1. Посмотри, какие фигуры противника на что нападают после твоего намеченного хода.',
            '2. Посмотри, какие твои фигуры защищены, а какие нет.',
            '3. Любая незащищённая фигура под боем — **подвешена**. Если не можешь её защитить или увести — не делай этот ход.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: у чёрных ход Кe5 выглядит активно, но оставляет слона c5 под ударом белого слона b4. Кe5 — ошибка, слона просто возьмут.',
            '',
            '**Ловушки с висячими фигурами.** Опытный противник иногда нарочно даёт тебе подвесить фигуру, а потом тактическим ударом забирает её. Поэтому сканируй не только свои, но и фигуры противника: его «подвешенные» фигуры — твой шанс.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: у белых на e4 стоит конь под двумя ударами (пешка d5 и конь f6) и только под одной защитой (пешка f3 отсутствует — защищает только пешка d3, но она тоже выйдет из игры). Чёрные играют dxe4 — выигрывают коня.',
            '',
            '**Регулярное сканирование висячих фигур — это 50% успеха на уровне начинающего.** Большинство партий выигрывается не комбинациями, а просто тем, что один игрок внимательнее другого.',
          ].join('\n'),
          diagrams: [
            { fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/1B2P3/3P1N2/PPP2PPP/RN1QKB1R b KQkq - 0 1', caption: 'Ход Кe5 оставит слона c5 под ударом слона b4 без защиты — потеря фигуры.', orientation: 'white' },
            { fen: 'r1bqkb1r/ppp2ppp/2n2n2/3pp3/4N3/3P4/PPP1PPPP/R1BQKBNR b KQkq - 0 1', caption: 'Конь e4 висит: на него нападают пешка d5 и конь f6, защитников мало. dxe4 — выигрыш фигуры.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.hanging-pieces.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.hanging-pieces.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.hanging-pieces.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.hanging-pieces.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.hanging-pieces.quiz.q2.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.hanging-pieces.quiz.q2.explanation` },
            { id: 'q3', promptI18nKey: `${BASE}.hanging-pieces.quiz.q3.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.hanging-pieces.quiz.q3.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.hanging-pieces.quiz.q3.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          selection: { mode: 'filter', themes: ['hangingPiece', 'oneMove'], ratingMax: 1200, limit: 6 },
          minSolved: 4,
        },
      },
    ],
  },
];
