import type { LessonFixture } from '../../../fixture-types';

const BLOCK = 'openings';
const BASE = 'lessons.beginner';

export const block04Openings: LessonFixture[] = [
  // 4.1 Три принципа дебюта
  {
    slug: 'opening-principles',
    order: 15,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.opening-principles.title`,
    summaryKey: `${BASE}.opening-principles.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Дебют — первая стадия партии, когда обе стороны выводят фигуры из начальной позиции. В этой стадии тебе нужно запомнить всего **три принципа** — они на 90% определяют здоровую игру:',
            '',
            '1. **Борись за центр.** Центральные поля (d4, d5, e4, e5) — самые важные. Фигура в центре контролирует больше клеток, а пешки в центре отнимают пространство у противника. Начинай партию с движения центральной пешки (1.e4 или 1.d4) и старайся ставить свои фигуры так, чтобы они влияли на центр.',
            '',
            '2. **Быстро развивай лёгкие фигуры.** Лёгкие фигуры — кони и слоны. Вывести все четыре лёгкие фигуры на активные клетки — главная задача первых 6–10 ходов. Ладьи и ферзь подключаются позже.',
            '',
            '3. **Уведи короля в безопасность рокировкой.** Король в центре — мишень. Как только линия для рокировки свободна, делай её. Обычно это 5-й — 8-й ходы.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: идеальный здоровый дебют. У белых пешка на e4 контролирует центр, выведены конь f3 и слон c4, король готов рокироваться. Ни одного пустого хода.',
            '',
            '**Чего избегать в дебюте:**',
            '- Не ходить одной и той же фигурой несколько раз без причины.',
            '- Не выводить рано ферзя — его будут гонять.',
            '- Не двигать лишние пешки (особенно на краях), пока не выведены фигуры.',
            '- Не играть «детский мат» против внимательного противника — это просто потеря темпов.',
          ].join('\n'),
          diagrams: [
            { fen: 'rnbqk2r/pppp1ppp/5n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1', caption: 'Здоровый дебют: центр занят, лёгкие фигуры выведены, рокировка готова.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.opening-principles.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.opening-principles.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.opening-principles.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.opening-principles.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.opening-principles.quiz.q2.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.opening-principles.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },

  // 4.2 Контроль центра
  {
    slug: 'center-control',
    order: 16,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.center-control.title`,
    summaryKey: `${BASE}.center-control.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Центр — четыре клетки **d4, d5, e4, e5**. Ещё иногда говорят о «расширенном центре» — это квадрат c3–f6.',
            '',
            '**Почему центр важен:**',
            '- Фигура в центре контролирует больше полей. Конь на e5 — 8 полей, конь на a1 — 2 поля.',
            '- Центральные пешки — «цепь», которая делит доску. Фигуры противника не могут легко перебраться с одного фланга на другой, если центр занят.',
            '- Из центра фигура быстро доберётся на любой фланг.',
            '',
            '{{diagram:0}}',
            '',
            '**Два способа контролировать центр:**',
            '',
            '1. **Занять его пешкой.** Ход 1.e4 сразу ставит пешку в центр. 1.d4 — то же самое. Это прямой способ.',
            '',
            '2. **Контролировать на расстоянии.** Ход 1.Кf3 не ставит пешку в центр, но контролирует поле e5. Позднее ты можешь сыграть d3 или c4 — и центр окажется в твоей власти без «физического» занятия. Такие дебюты называются **гипермодернистскими** (например, дебют Рети).',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: белые разыграли классический дебют с пешками в центре (e4-d4). Чёрные ответили гипермодернистски — контролируют центр фигурами с флангов. Оба подхода рабочие.',
            '',
            '**Правило для начинающего:** пока идёт освоение шахмат, играй классически — занимай центр пешкой e4 или d4 и развивай фигуры под его прикрытием. Гипермодернизм требует более тонкого понимания.',
          ].join('\n'),
          diagrams: [
            // KS-1779 / KS-1778: консистентно с уроком 1.3 — короли в h8/h1.
            { fen: '7k/8/8/4N3/8/8/8/7K w - - 0 1', caption: 'Конь в центре — 8 полей. Сравни с конём в углу (2 поля).', orientation: 'white' },
            { fen: 'rnbqkb1r/pp3ppp/3ppn2/8/3PP3/2N5/PPP2PPP/R1BQKBNR w KQkq - 0 1', caption: 'Белые заняли центр пешками, чёрные контролируют его фигурами — обе стратегии рабочие.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.center-control.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.center-control.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.center-control.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.center-control.quiz.q2.prompt`,
              options: ['a','b','c','d'].map((o) => ({ id: o, labelI18nKey: `${BASE}.center-control.quiz.q2.opt.${o}` })),
              correctOptionIds: ['c'], explanationI18nKey: `${BASE}.center-control.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },

  // 4.3 Развитие фигур
  {
    slug: 'piece-development',
    order: 17,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.piece-development.title`,
    summaryKey: `${BASE}.piece-development.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Развитие** — вывод фигур из начальной позиции на активные поля. Здоровое развитие подчиняется правилам:',
            '',
            '1. **Лёгкие фигуры (кони и слоны) — раньше тяжёлых (ферзь и ладьи).** Тяжёлые фигуры в дебюте уязвимы: на них нападают с темпом. Лёгкие фигуры проще защищать и активнее участвуют в дебютной борьбе.',
            '',
            '2. **Кони раньше слонов.** У коней меньше вариантов выхода (обычно c3/f3 для белых), у слонов — больше. Сначала определись с конями, потом под них выбирай слонам поля.',
            '',
            '3. **Каждой фигурой — по одному разу в дебюте.** Если ходишь два раза одной и той же фигурой без серьёзного повода, противник успевает развить больше фигур — теряешь темп.',
            '',
            '4. **Ладьи — после рокировки.** Ладья автоматически выходит на центральную вертикаль при рокировке. Отдельно её трогать до этого обычно нет смысла.',
            '',
            '5. **Ферзь — последним и с конкретной целью.** Выводить ферзя, пока лёгкие фигуры на своих местах — плохо.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: у белых правильное развитие — кони f3 и c3, слоны c4 и e3, рокировка сделана. Восемь ходов — полный порядок.',
            '',
            '**Куда ставить коней:**',
            '- Кb1 обычно идёт на c3 (контроль центра, d5, e4).',
            '- Кg1 обычно идёт на f3 (контроль e5, поддержка d4).',
            '',
            '**Куда ставить слонов:**',
            '- Белопольный слон f1 — на c4, b5, d3 или e2.',
            '- Чернопольный слон c1 — на g5, f4, e3 или b2 (после b3).',
            '',
            'Нет «единственного правильного» развития — выбор зависит от дебюта.',
          ].join('\n'),
          diagrams: [
            { fen: 'r1bq1rk1/pppp1ppp/2n2n2/4p3/2B1P3/2NPBN2/PPP2PPP/R2QK2R w KQ - 0 1', caption: 'Правильная расстановка: все четыре лёгкие фигуры и рокировка. Можно начинать игру в центре.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.piece-development.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.piece-development.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.piece-development.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.piece-development.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.piece-development.quiz.q2.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.piece-development.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },

  // 4.4 Рокировка
  {
    slug: 'castling-when',
    order: 18,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.castling-when.title`,
    summaryKey: `${BASE}.castling-when.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Рокировка — важнейший ход дебюта. Она решает две задачи сразу:',
            '- Уводит короля с центра, где он может попасть под атаку.',
            '- Выводит ладью на центральную вертикаль, где она будет работать в миттельшпиле.',
            '',
            '**Когда рокироваться.** В большинстве дебютов — как только лёгкие фигуры на королевском фланге выведены (конь на f3, слон на e2/d3/c4) и между королём и ладьёй пусто. Обычно это 4–7 ходы.',
            '',
            '**Короткая или длинная.**',
            '- **Короткая рокировка (O-O)** — стандартная. Быстрее (фигур между королём и ладьёй только 3), безопаснее (король стоит ближе к углу), подходит в 90% партий.',
            '- **Длинная рокировка (O-O-O)** — агрессивнее. Ладья сразу попадает на d1 — центральную вертикаль. Используется, когда хочется быстро начать атаку по d- или c-линии. Но длинная рокировка дольше готовится (нужно вывести ферзя и слона c1, между ними и ладьёй a1 находится 4 фигуры) и король стоит ближе к центру, более уязвим.',
            '',
            '{{diagram:0}}',
            '',
            '**Почему не затягивать рокировку.** Король в центре — риск открытой линии e или d. Если противник первым вскроет центр, твой король попадёт под прицел ладей и ферзя.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: чёрные не успели рокироваться и жадничают пешкой e. Белые вскрывают центр ходом d5 и выигрывают фигуру — короля нельзя бросать в центре.',
            '',
            '**Правило:** если нет веской причины отложить рокировку — делай её. Откладывать рокировку для «более выгодного момента» на уровне начинающего обычно заканчивается тем, что этот момент не наступает.',
          ].join('\n'),
          diagrams: [
            { fen: 'rnbqk2r/ppp2ppp/3p1n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQ1RK1 b kq - 0 1', caption: 'Белые рокировались вовремя. Король в безопасности, ладья f1 уже работает.', orientation: 'white' },
            { fen: 'rnbqkb1r/ppp2ppp/5n2/3pp3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1', caption: 'Чёрные не рокировались. При вскрытии центра король остаётся под ударом.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.castling-when.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.castling-when.quiz.q1.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.castling-when.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.castling-when.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.castling-when.quiz.q2.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.castling-when.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },

  // 4.5 Типичные ошибки
  {
    slug: 'opening-mistakes',
    order: 19,
    blockKey: BLOCK,
    kind: 'theory',
    estMinutes: 10,
    titleKey: `${BASE}.opening-mistakes.title`,
    summaryKey: `${BASE}.opening-mistakes.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Самые частые ошибки начинающих в дебюте. Если ты их избегаешь — уже выигрываешь половину партий.',
            '',
            '**1. Ранний выход ферзя.** Ферзь — дорогая фигура, противник с удовольствием на него нападёт лёгкой фигурой и выиграет темп. После партии оказывается, что ты сделал 5 ходов ферзём, а у противника уже все фигуры развиты.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: типичная ошибка — 2.Фh5? Чёрные отвечают 2...Кc6 (защищают пешку e5 и развивают фигуру), и ферзь вынужден отступать. Белые потеряли темп.',
            '',
            '**2. «Пешкоедство» — ловля пешек дебюта в ущерб развитию.** На какой-то момент соперник оставит пешку под ударом. Если ради неё ты оторвёшь фигуру от развития, часто получится так, что фигуру взаперти на краю и ещё хуже — соперник ловит её в ловушку.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: 8.Фxb7?? — белые взяли пешку ферзём, но 8...Кd4 — ферзь пойман, отступить почти некуда без потерь. Классическая ловушка.',
            '',
            '**3. Движение одной и той же фигурой много раз.** Ты выводишь коня на f3, потом двигаешь его на e5, потом возвращаешь на f3. Три хода — один конь. Противник за то же время вывел трёх разных фигур.',
            '',
            '**4. Слишком много пешечных ходов.** Каждый ход, не выводящий фигуру — подарок противнику. Ходы типа h3, a3, b3 в начале партии обычно не нужны, если нет конкретной цели.',
            '',
            '**5. Забыли защитить пешку f7/f2.** Пункт f7 (f2 для белых) защищён только королём, это вечная уязвимость. Атаки на f7 (Qh5+Bc4, «пастушеский мат», тактика с Кg5) — стандартный набор, надо быть готовым.',
          ].join('\n'),
          diagrams: [
            { fen: 'rnbqkbnr/pppp1ppp/8/4p2Q/4P3/8/PPPP1PPP/RNB1KBNR b KQkq - 2 2', caption: 'Ранний выход ферзя на h5. После 2...Кc6 белые теряют темп.', orientation: 'white' },
            { fen: 'r1b1kbnr/pp1ppppp/1qn5/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 0 1', caption: 'Типовая ловушка: после Фxb7 чёрные ходом Кd4 или Ка5 ловят ферзя.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.opening-mistakes.quiz.q1.prompt`,
              options: ['a','b','c','d'].map((o) => ({ id: o, labelI18nKey: `${BASE}.opening-mistakes.quiz.q1.opt.${o}` })),
              correctOptionIds: ['d'], explanationI18nKey: `${BASE}.opening-mistakes.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.opening-mistakes.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.opening-mistakes.quiz.q2.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.opening-mistakes.quiz.q2.explanation` },
            { id: 'q3', promptI18nKey: `${BASE}.opening-mistakes.quiz.q3.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.opening-mistakes.quiz.q3.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.opening-mistakes.quiz.q3.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
    ],
  },
];
