import type { LessonFixture } from '../../../fixture-types';

const BLOCK = 'tactics';
const BASE = 'lessons.beginner';

export const block05Tactics: LessonFixture[] = [
  // 5.1 Вилка
  {
    slug: 'fork',
    order: 20,
    blockKey: BLOCK,
    kind: 'tactics_set',
    estMinutes: 12,
    titleKey: `${BASE}.fork.title`,
    summaryKey: `${BASE}.fork.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Вилка** — это один из самых распространённых тактических приёмов. Одна твоя фигура нападает одновременно на две (или больше) фигуры противника. Он защитит одну — ты заберёшь другую.',
            '',
            '**Вилки ставят все фигуры**, но чаще всего вилку делает конь: из-за L-образного хода он нападает на поля, которые сложно прикрыть одним ходом, и его сложно «отогнать».',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме классическая вилка конём: Кc7+ атакует чёрного короля на e8 и ладью a8 одновременно. Король уходит от шаха — конь берёт ладью. Приём называется **«семейный шах»**, когда вилка захватывает короля и другую фигуру.',
            '',
            '**Виды вилок:**',
            '- **Вилка конём** — самая частая. Часто со шахом.',
            '- **Вилка пешкой** — пешка бьёт по двум диагоналям, поэтому может напасть на две фигуры сразу.',
            '- **Вилка ферзём** — из-за универсальности ферзя он может создать вилку в любой момент.',
            '- **Вилка слоном или ладьёй** — реже, но встречается.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме — вилка пешкой: после d4-d5 пешка нападает одновременно на коня c6 и коня e6 (или слон на e6). Одного из них белые заберут.',
            '',
            '**Как искать вилки.** Смотри на фигуры противника, стоящие «недалеко» друг от друга на расстоянии хода коня, или на расстоянии взятия пешкой. Если между ними есть общая «целевая» клетка — там возможна вилка.',
          ].join('\n'),
          diagrams: [
            { fen: 'r3k3/8/2N5/8/8/8/8/4K3 w - - 0 1', caption: '«Семейный шах» — конь c6 даёт шах королю и одновременно нападает на ладью.', orientation: 'white' },
            { fen: '4k3/8/2n1n3/3P4/8/8/8/4K3 w - - 0 1', caption: 'Пешечная вилка: d5 нападает и на коня c6, и на коня e6.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.fork.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.fork.quiz.q1.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.fork.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.fork.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.fork.quiz.q2.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.fork.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          selection: { mode: 'filter', themes: ['fork'], ratingMin: 600, ratingMax: 1300, limit: 8 },
          minSolved: 5,
        },
      },
    ],
  },

  // 5.2 Связка
  {
    slug: 'pin',
    order: 21,
    blockKey: BLOCK,
    kind: 'tactics_set',
    estMinutes: 12,
    titleKey: `${BASE}.pin.title`,
    summaryKey: `${BASE}.pin.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Связка** — это линейная атака, в которой твоя дальнобойная фигура (ладья, слон или ферзь) нападает на фигуру противника, за которой стоит другая его фигура. Если передняя уйдёт, ты возьмёшь ту, что была за ней.',
            '',
            'Есть два вида:',
            '',
            '**Полная (абсолютная) связка** — за связанной фигурой стоит **король**. По правилам двигать связанную фигуру **нельзя**: это откроет шах собственному королю.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме — слон d3 связывает чёрного коня f5 с королём g8. Конь не может ходить: любое его движение — шах белого слона. Белые могут спокойно атаковать коня (например, g4) и выиграть его.',
            '',
            '**Неполная (относительная) связка** — за связанной фигурой стоит **ценная фигура, но не король**. Связанную фигуру **технически можно двинуть**, но тогда за ней откроется более ценная.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме — ладья e1 связывает коня e5 с ферзём e8. Конь двигаться может, но после любого его хода белые возьмут ферзя.',
            '',
            '**Как пользоваться связкой:**',
            '1. Нападай ещё одной фигурой на связанную — она не может убежать.',
            '2. Подкрепляй атаку пешкой: g4, h4 — и связанная фигура в итоге теряется.',
            '3. Не позволяй противнику развязаться: если он собирается переставить короля или загородиться фигурой — помешай.',
            '',
            '**Защита от связки:** уйти королём (для полной связки), поставить «блокиратор» между связанной фигурой и той, что за ней, или взять связывающую фигуру, если это возможно.',
          ].join('\n'),
          diagrams: [
            { fen: '4k1r1/5ppp/8/5n2/8/3B4/8/4K3 b - - 0 1', caption: 'Полная связка: конь f5 прикован к королю, двигаться не может.', orientation: 'white' },
            { fen: '4q2k/8/8/4n3/8/8/4R3/4K3 w - - 0 1', caption: 'Относительная связка: коня e5 можно двигать, но тогда теряется ферзь.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.pin.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.pin.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.pin.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.pin.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.pin.quiz.q2.opt.${o}` })),
              correctOptionIds: ['c'], explanationI18nKey: `${BASE}.pin.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          selection: { mode: 'filter', themes: ['pin'], ratingMin: 600, ratingMax: 1300, limit: 8 },
          minSolved: 5,
        },
      },
    ],
  },

  // 5.3 Двойной удар
  {
    slug: 'double-attack',
    order: 22,
    blockKey: BLOCK,
    kind: 'tactics_set',
    estMinutes: 10,
    titleKey: `${BASE}.double-attack.title`,
    summaryKey: `${BASE}.double-attack.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Двойной удар** — более широкое понятие, чем вилка. Это ситуация, когда один твой ход создаёт **две угрозы одновременно**, парировать которые одним ходом противник не может.',
            '',
            'Вилка — частный случай двойного удара (нападение одной фигурой на две). Но двойной удар может быть и «распределённым»: одна фигура нападает, а другая в это же время угрожает матом или захватом.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: ход Фd5 создаёт сразу две угрозы — мат на f7 и взятие ладьи a8. Защититься от обеих не получится.',
            '',
            '**Типовые примеры:**',
            '- Ход с шахом, одновременно нападающий на ферзя или ладью.',
            '- Ход, открывающий угрозу матом, и параллельно атакующий фигуру.',
            '- Ход, создающий угрозу связки или вилки, и одновременно выигрывающий пешку.',
            '',
            '**Как искать двойные удары.** Смотри не только на «чистые» вилки. После твоего хода проверь: **какие две угрозы возникли**? Если хотя бы две, и парировать обе нельзя — это сильный ход.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: ход Кd5 одновременно нападает на ферзя c7 и на слона e7 (и на него же нападает слон c5). Противник спасает ферзя, белые забирают слона.',
          ].join('\n'),
          diagrams: [
            { fen: 'r5k1/4bppp/8/3Q4/8/8/8/4K3 w - - 0 1', caption: 'Ферзь d5 создаёт мат-угрозу на f7 и одновременно нападает на ладью a8. Двойной удар.', orientation: 'white' },
            { fen: '4k3/2q1b3/8/8/8/8/4N3/4K3 w - - 0 1', caption: 'Кd5 атакует одновременно ферзя c7 и слона e7.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.double-attack.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.double-attack.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.double-attack.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.double-attack.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.double-attack.quiz.q2.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.double-attack.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          // chess-expert указал ['doubleAttack', 'fork'], но Lichess puzzle
          // themes не содержат 'doubleAttack' — используем 'fork' как ближайшую
          // (уровень начинающего, фильтр по рейтингу и так срежет сложные).
          selection: { mode: 'filter', themes: ['fork'], ratingMin: 700, ratingMax: 1300, limit: 8 },
          minSolved: 5,
        },
      },
    ],
  },

  // 5.4 Вскрытое нападение
  {
    slug: 'discovered-attack',
    order: 23,
    blockKey: BLOCK,
    kind: 'tactics_set',
    estMinutes: 12,
    titleKey: `${BASE}.discovered-attack.title`,
    summaryKey: `${BASE}.discovered-attack.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Вскрытое нападение** — это когда ты ходишь одной фигурой, а атаку на противника открывает **другая** твоя фигура, которая стояла за первой и до хода не могла атаковать.',
            '',
            'Это очень сильный приём: фигура, которая ходит, часто одновременно делает свою угрозу. Получается **два удара за один ход**.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: белые играют Кd4. Конь с e2 уходит с линии, и ладья e1 открывает атаку на ферзя e8. Одновременно сам конь на d4 нападает на ладью c6. Чёрные спасают ферзя — белые берут ладью.',
            '',
            '**Составные элементы приёма:**',
            '1. Фигура «перекрывающая» — та, которая ходит и уходит с линии.',
            '2. Фигура «стреляющая» — дальнобойная (ладья, слон или ферзь), которая была перекрыта и теперь атакует.',
            '3. Цель — фигура противника, на которую открывается атака.',
            '',
            '**Виды вскрытых нападений:**',
            '- Обычное вскрытое нападение.',
            '- **Вскрытый шах** — атака открывается на короля. Противник обязан парировать шах, твоя ходящая фигура свободна делать что угодно (даже забирать ферзя).',
            '- **Двойной шах** — ходящая фигура тоже даёт шах. От двойного шаха можно защититься **только уходом короля** — закрыть или взять обе атакующие фигуры одним ходом нельзя.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме — двойной шах: ход Кf6+ даёт шах конём, а открывает шах слоном c4. Спастись можно только королём.',
            '',
            '**Как ставить вскрытое нападение.** Ищи ситуации, где две твои фигуры стоят на одной линии с фигурой противника. Когда между ними только твоя фигура — её ход откроет атаку.',
          ].join('\n'),
          diagrams: [
            // KS-1779 / KS-1778: чёрный король на a8 (рекомендация chess-expert).
            { fen: 'k3q3/8/2r5/8/8/8/4N3/4R2K w - - 0 1', caption: 'Конь e2 уходит на d4 — открывает ладью e1 на ферзя и одновременно нападает на ладью c6.', orientation: 'white' },
            { fen: '4k3/8/5N2/8/2B5/8/8/4K3 w - - 0 1', caption: 'Двойной шах Кf6+ даёт шах конём и слоном одновременно.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.discovered-attack.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.discovered-attack.quiz.q1.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.discovered-attack.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.discovered-attack.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.discovered-attack.quiz.q2.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.discovered-attack.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          selection: { mode: 'filter', themes: ['discoveredAttack'], ratingMin: 700, ratingMax: 1400, limit: 6 },
          minSolved: 4,
        },
      },
    ],
  },

  // 5.5 Открытый шах
  {
    slug: 'discovered-check',
    order: 24,
    blockKey: BLOCK,
    kind: 'tactics_set',
    estMinutes: 10,
    titleKey: `${BASE}.discovered-check.title`,
    summaryKey: `${BASE}.discovered-check.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            '**Открытый (вскрытый) шах** — это вскрытое нападение, в котором открывается шах королю противника. Самое сильное, что у этого приёма есть: **ходящая фигура ни перед кем не обязана**. Она может встать куда угодно — бить, ходить на пустое поле, даже встать под удар — противник обязан сначала парировать шах, а уже потом разбираться с ходящей фигурой.',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: ход Кd7 открывает шах ладьи e1 королю e8. Одновременно конь нападает на ферзя f6. Чёрные обязаны ответить на шах (например, Фe6 или уйти королём), а потом уже думать про коня — белые его спокойно уведут, выиграв ферзя.',
            '',
            '**«Конь-мельница».** Классическая конструкция с открытыми шахами — конь циклично прыгает, каждый раз открывая шах ладьёй, каждый раз забирая что-то. Противник не может уйти, пока не взят весь материал на линии.',
            '',
            '**Двойной шах.** Самый опасный случай. Шах дают одновременно:',
            '- Ходящая фигура.',
            '- Фигура, которую она открыла.',
            '',
            'От двойного шаха **единственная защита — ход королём**. Ни закрыться, ни взять одну из атакующих нельзя, потому что вторая продолжит шаховать.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме — двойной шах: ход Kf6+ даёт шах конём, слон c4 открывает шах по диагонали. Король чёрных обязан ходить, но у него нет полей — мат.',
            '',
            '**Где искать вскрытые шахи.** Смотри на своего короля и на его короля: если между ним и твоей дальнобойной фигурой стоит только твоя фигура — её ход даст шах. Дальше дело техники.',
          ].join('\n'),
          diagrams: [
            { fen: '4k3/8/5q2/8/4N3/8/8/4R1K1 w - - 0 1', caption: 'Кd7 открывает шах ладьи на короля, одновременно нападает на ферзя. Выигрыш ферзя.', orientation: 'white' },
            { fen: '5k2/8/4N3/8/2B5/8/5PPP/6K1 w - - 0 1', caption: 'Кf6 — двойной шах. Король обязан ходить, но легальных полей нет — мат.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.discovered-check.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.discovered-check.quiz.q1.opt.${o}` })),
              correctOptionIds: ['a'], explanationI18nKey: `${BASE}.discovered-check.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.discovered-check.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.discovered-check.quiz.q2.opt.${o}` })),
              correctOptionIds: ['c'], explanationI18nKey: `${BASE}.discovered-check.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          selection: { mode: 'filter', themes: ['discoveredAttack', 'doubleCheck'], ratingMin: 800, ratingMax: 1400, limit: 5 },
          minSolved: 3,
        },
      },
    ],
  },

  // 5.6 Мат в 1 и мат в 2
  {
    slug: 'mate-in-one-two',
    order: 25,
    blockKey: BLOCK,
    kind: 'tactics_set',
    estMinutes: 15,
    titleKey: `${BASE}.mate-in-one-two.title`,
    summaryKey: `${BASE}.mate-in-one-two.summary`,
    isPublished: true,
    steps: [
      {
        id: 'intro',
        order: 0,
        payload: {
          type: 'text',
          bodyMarkdown: [
            'Решение задач «мат в 1 ход» и «мат в 2 хода» — основа тактического зрения. Все более сложные комбинации строятся на той же способности: увидеть, куда идут фигуры, и понять, какие поля у короля свободны.',
            '',
            '**Алгоритм поиска мата в 1 ход:**',
            '1. Где король противника?',
            '2. Какие поля вокруг него есть (всего до 8)?',
            '3. Какие из этих полей атакуют мои фигуры? Какие — не атакуют?',
            '4. Могу ли я атаковать короля **и одновременно отрезать все поля побега**?',
            '',
            '{{diagram:0}}',
            '',
            'На диаграмме: белые ставят мат одним ходом. Король h8 зажат своими пешками g7, h7. Ход Rh1-h8 — шах ладьёй, королю некуда уйти, никто не может закрыться или взять ладью. Мат.',
            '',
            '**Мат в 2 хода** — сложнее. Нужно найти:',
            '1. Твой ход, который создаёт неотразимую угрозу мата.',
            '2. Любой ответ противника.',
            '3. Твой следующий ход, который ставит мат.',
            '',
            'Ключевой приём — **«тихий ход»**: иногда первый ход — не шах, а подготовка. Например, ход, закрывающий поле побега королю.',
            '',
            '{{diagram:1}}',
            '',
            'На диаграмме: мат в 2. 1.Фg7+!? — плохо, король уходит. 1.Кe7! — тихий ход, который перекрывает поле f5. Теперь на любой ход чёрных у белых следующий ход — Фf7# (у короля отрезаны все поля).',
            '',
            '**Почему важно тренировать маты в 1-2.** Все тактические комбинации в партии — это, по сути, «мат в N» или «выигрыш материала в N». Умение быстро считать короткие маты равносильно умению быстро считать всё остальное.',
          ].join('\n'),
          diagrams: [
            { fen: '6k1/5ppp/8/8/8/8/8/K6R w - - 0 1', caption: 'Мат в 1: Rh1-h8#. Король заперт пешками, ладья атакует 8-ю горизонталь.', orientation: 'white' },
            { fen: '5k2/5p2/4N3/8/4Q3/8/8/6K1 w - - 0 1', caption: 'Мат в 2: Ne6 (тихий ход, закрывающий f5+e7), затем Qe8#.', orientation: 'white' },
          ],
        },
      },
      {
        id: 'quiz',
        order: 1,
        payload: {
          type: 'quiz',
          questions: [
            { id: 'q1', promptI18nKey: `${BASE}.mate-in-one-two.quiz.q1.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.mate-in-one-two.quiz.q1.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.mate-in-one-two.quiz.q1.explanation` },
            { id: 'q2', promptI18nKey: `${BASE}.mate-in-one-two.quiz.q2.prompt`,
              options: ['a','b','c'].map((o) => ({ id: o, labelI18nKey: `${BASE}.mate-in-one-two.quiz.q2.opt.${o}` })),
              correctOptionIds: ['b'], explanationI18nKey: `${BASE}.mate-in-one-two.quiz.q2.explanation` },
          ],
          passThreshold: 0.7,
        },
      },
      {
        id: 'practice',
        order: 2,
        payload: {
          type: 'puzzle',
          selection: { mode: 'filter', themes: ['mateIn1', 'mateIn2'], ratingMin: 500, ratingMax: 1200, limit: 10 },
          minSolved: 7,
        },
      },
    ],
  },
];
