-- AlterTable
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "format" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "time_control" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "location" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "players" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "standings_url" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "image_url" TEXT;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "start_date" TIMESTAMP;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "end_date" TIMESTAMP;
ALTER TABLE "broadcasts" ADD COLUMN IF NOT EXISTS "streams" JSONB;
