export {
  useBoardSettingsContext as useBoardSettings,
  BoardSettingsProvider,
  BoardSettingsContext,
  BOARD_THEMES,
  PIECE_SETS,
  BOARD_SIZES,
  SIDEBAR_FONT_SIZES,
  NAV_AUTO_REPEAT_SPEEDS,
  NAV_AUTO_REPEAT_MS_MIN,
  NAV_AUTO_REPEAT_MS_MAX,
  NAV_AUTO_REPEAT_MS_STEP,
  NAV_AUTO_REPEAT_MS_DEFAULT,
} from '../context/BoardSettingsContext';
export type {
  BoardThemeId,
  PieceSetId,
  BoardTheme,
  PieceSet,
  InputMode,
  BoardSizeId,
  BoardSizePreset,
  SidebarFontSizeId,
  SidebarFontSizePreset,
  NavAutoRepeatSpeedId,
  NavAutoRepeatSpeedPreset,
} from '../context/BoardSettingsContext';
