const ECO_DATA: [string, string][] = [
  ['e4', "King's Pawn Opening"],
  ['d4', "Queen's Pawn Opening"],
  ['c4', 'English Opening'],
  ['Nf3', 'Reti Opening'],
  ['f4', "Bird's Opening"],
  ['g3', 'Hungarian Opening'],
  ['b3', 'Nimzo-Larsen Attack'],
  ['b4', 'Sokolsky Opening'],
  ['e4 c5', 'Sicilian Defense'],
  ['e4 c5 Nf3', 'Sicilian Defense'],
  ['e4 c5 Nf3 d6', 'Sicilian Defense'],
  ['e4 c5 Nf3 d6 d4', 'Sicilian Defense'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4', 'Sicilian Defense: Open'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3', 'Sicilian Defense: Najdorf Variation'],
  ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6', 'Sicilian Defense: Najdorf Variation'],
  ['e4 c5 Nf3 Nc6', 'Sicilian Defense'],
  ['e4 c5 Nf3 e6', 'Sicilian Defense'],
  ['e4 c5 Nc3', 'Sicilian Defense: Closed'],
  ['e4 e6', 'French Defense'],
  ['e4 e6 d4', 'French Defense'],
  ['e4 e6 d4 d5', 'French Defense'],
  ['e4 e6 d4 d5 Nc3', 'French Defense'],
  ['e4 e6 d4 d5 Nd2', 'French Defense: Tarrasch Variation'],
  ['e4 e6 d4 d5 e5', 'French Defense: Advance Variation'],
  ['e4 c6', 'Caro-Kann Defense'],
  ['e4 c6 d4', 'Caro-Kann Defense'],
  ['e4 c6 d4 d5', 'Caro-Kann Defense'],
  ['e4 c6 d4 d5 Nc3', 'Caro-Kann Defense: Main Line'],
  ['e4 c6 d4 d5 e5', 'Caro-Kann Defense: Advance Variation'],
  ['e4 d5', 'Scandinavian Defense'],
  ['e4 d6', 'Pirc Defense'],
  ['e4 d6 d4 Nf6 Nc3', 'Pirc Defense'],
  ['e4 g6', 'Modern Defense'],
  ['e4 Nf6', "Alekhine's Defense"],
  ['e4 e5', "King's Pawn Game"],
  ['e4 e5 Nf3', "King's Knight Opening"],
  ['e4 e5 Nf3 Nc6', "King's Knight Opening"],
  ['e4 e5 Nf3 Nc6 Bb5', 'Ruy Lopez'],
  ['e4 e5 Nf3 Nc6 Bb5 a6', 'Ruy Lopez'],
  ['e4 e5 Nf3 Nc6 Bb5 a6 Ba4', 'Ruy Lopez'],
  ['e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6', 'Ruy Lopez'],
  ['e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O', 'Ruy Lopez'],
  ['e4 e5 Nf3 Nc6 Bc4', 'Italian Game'],
  ['e4 e5 Nf3 Nc6 Bc4 Bc5', 'Italian Game: Giuoco Piano'],
  ['e4 e5 Nf3 Nc6 Bc4 Nf6', 'Italian Game: Two Knights Defense'],
  ['e4 e5 Nf3 Nc6 d4', 'Scotch Game'],
  ['e4 e5 Nf3 Nc6 d4 exd4', 'Scotch Game'],
  ['e4 e5 Nf3 Nf6', "Petrov's Defense"],
  ['e4 e5 Nf3 d6', 'Philidor Defense'],
  ['e4 e5 f4', "King's Gambit"],
  ['e4 e5 d4', 'Center Game'],
  ['e4 e5 Bc4', "Bishop's Opening"],
  ['d4 d5', "Queen's Pawn Game"],
  ['d4 d5 c4', "Queen's Gambit"],
  ['d4 d5 c4 e6', "Queen's Gambit Declined"],
  ['d4 d5 c4 e6 Nc3', "Queen's Gambit Declined"],
  ['d4 d5 c4 e6 Nc3 Nf6', "Queen's Gambit Declined"],
  ['d4 d5 c4 e6 Nf3', "Queen's Gambit Declined"],
  ['d4 d5 c4 dxc4', "Queen's Gambit Accepted"],
  ['d4 d5 c4 c6', 'Slav Defense'],
  ['d4 d5 c4 c6 Nf3 Nf6', 'Slav Defense'],
  ['d4 d5 Nf3', "Queen's Pawn Game"],
  ['d4 d5 Nf3 Nf6', "Queen's Pawn Game"],
  ['d4 d5 Bf4', 'London System'],
  ['d4 d5 Nf3 Nf6 Bf4', 'London System'],
  ['d4 Nf6', 'Indian Defense'],
  ['d4 Nf6 c4', 'Indian Defense'],
  ['d4 Nf6 c4 e6', 'Indian Defense'],
  ['d4 Nf6 c4 e6 Nc3', 'Nimzo-Indian Defense'],
  ['d4 Nf6 c4 e6 Nc3 Bb4', 'Nimzo-Indian Defense'],
  ['d4 Nf6 c4 e6 Nf3', 'Indian Defense'],
  ['d4 Nf6 c4 e6 Nf3 b6', "Queen's Indian Defense"],
  ['d4 Nf6 c4 e6 g3', 'Catalan Opening'],
  ['d4 Nf6 c4 g6', "King's Indian Defense"],
  ['d4 Nf6 c4 g6 Nc3', "King's Indian Defense"],
  ['d4 Nf6 c4 g6 Nc3 Bg7', "King's Indian Defense"],
  ['d4 Nf6 c4 g6 Nc3 Bg7 e4', "King's Indian Defense"],
  ['d4 Nf6 c4 g6 Nc3 Bg7 e4 d6', "King's Indian Defense"],
  ['d4 Nf6 c4 c5', 'Benoni Defense'],
  ['d4 Nf6 Nf3', 'Indian Defense'],
  ['d4 Nf6 Nf3 g6', "King's Indian Defense"],
  ['d4 Nf6 Bf4', 'London System'],
  ['d4 Nf6 Nf3 d5 Bf4', 'London System'],
  ['c4 e5', 'English Opening: Reversed Sicilian'],
  ['c4 Nf6', 'English Opening: Anglo-Indian'],
  ['c4 c5', 'English Opening: Symmetrical'],
  ['Nf3 d5', 'Reti Opening'],
  ['Nf3 d5 c4', 'Reti Opening'],
  ['Nf3 Nf6', 'Reti Opening'],
];

const ecoMap = new Map<string, string>(ECO_DATA);

export function classifyOpening(sanMoves: string[]): string {
  let best = '';
  for (let len = 1; len <= Math.min(sanMoves.length, 20); len++) {
    const key = sanMoves.slice(0, len).join(' ');
    const name = ecoMap.get(key);
    if (name) best = name;
  }
  return best;
}
