import type { CourseFixture } from '../types/editor';

/**
 * Генерирует текст TS-модуля в формате seed-фикстуры для вставки в
 * `apps/api/src/lessons/seed/courses/<slug>/index.ts` (L-27 / KS-1805).
 *
 * Формат ориентирован на backend'ный `CourseFixture` (`fixture-types.ts`):
 * `default export` — объект с полями курса и `lessons: LessonFixture[]`,
 * где каждый lesson содержит `steps: StepFixture[]`.
 *
 * Правила:
 * - client-side `id` полей (`StepFixture.id`, `LessonFixture.id`) из
 *   state'а редактора в экспорт НЕ попадают — seed-линтер сам назначит
 *   стабильные ключи (в БД id = UUID).
 * - `order` дублируется из индекса массива, но оставляем явным полем
 *   для читаемости seed'а.
 * - Значения сериализуются через `JSON.stringify` с отступом 2, затем
 *   заменяются двойные кавычки вокруг ключей на «без кавычек» в
 *   простых случаях (`"key":` → `key:`). Это косметика: результат всё
 *   равно parse-корректный TS — если автор хочет идеал, он прогонит
 *   файл через prettier руками.
 *
 * Функция — чистая и тестируемая; возвращает строку.
 */

export function exportCourseFixture(course: CourseFixture): string {
  const lessons = course.lessons
    .slice()
    .sort((a, b) => a.order - b.order)
    .map((lesson) => ({
      slug: lesson.slug,
      order: lesson.order,
      blockKey: lesson.blockKey,
      kind: lesson.kind,
      titleI18nKey: lesson.titleI18nKey,
      summaryI18nKey: lesson.summaryI18nKey,
      estMinutes: lesson.estMinutes,
      steps: lesson.steps
        .slice()
        .sort((a, b) => a.order - b.order)
        .map((step) => ({
          order: step.order,
          type: step.type,
          payload: step.payload,
        })),
    }));

  const data = {
    slug: course.slug,
    level: course.level,
    titleI18nKey: course.titleI18nKey,
    descriptionI18nKey: course.descriptionI18nKey,
    order: course.order,
    isPublished: course.isPublished,
    lessons,
  };

  const json = JSON.stringify(data, null, 2);
  // Делаем out простым TS: `export default <json>;` + prettify ключей.
  const tsBody = stripQuotesFromSimpleKeys(json);

  return [
    `// Auto-generated by /lessons/editor (KS-1805).`,
    `// Скопируй этот файл в apps/api/src/lessons/seed/courses/${course.slug || '<slug>'}/index.ts`,
    `// и прогони seed-линтер локально перед коммитом.`,
    ``,
    `import type { CourseFixture } from '../../fixture-types';`,
    ``,
    `const course: CourseFixture = ${tsBody};`,
    ``,
    `export default course;`,
    ``,
  ].join('\n');
}

/**
 * Превращает `"simpleKey":` в `simpleKey:`. Для ключей с дефисом, точкой,
 * пробелом и т.п. кавычки оставляем (валидный TS требует их). Работает
 * построчно, чтобы не задеть строковые значения с символом `:` внутри.
 */
function stripQuotesFromSimpleKeys(json: string): string {
  return json.replace(
    /(^|[,{\s])"([A-Za-z_$][A-Za-z0-9_$]*)":/g,
    (_match, prefix: string, key: string) => `${prefix}${key}:`,
  );
}

/**
 * Триггерит скачивание файла в браузере. Изолировано в отдельную функцию,
 * чтобы JSDOM-тестам было достаточно замокать `download` без реального
 * DOM-клика.
 */
export function triggerDownload(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // revokeObjectURL после небольшого delay — Safari иначе обрывает загрузку.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
